const translations = {
  en: {
    nav_assetiq: "AssetIQ",
    nav_maintainai: "MaintainAI",
    nav_customers: "Customers",
    nav_pricing: "Pricing",
    nav_login: "Log in",
    nav_demo: "Get a Demo",

    hero_badge: "Trusted by 400+ industrial enterprises",
    hero_h1: "Your machines are talking.<br />Are you listening?",
    hero_sub: "NovaTerra connects your factory floor to your business layer — real-time asset visibility, AI-driven maintenance, and zero unplanned downtime.",
    hero_cta1: "Book a Demo",
    hero_cta2: "See the Platform →",

    logos_label: "Powering operations at",

    problem_h2: "Unplanned downtime costs manufacturers <span class='highlight'>$260,000 per hour.</span>",
    problem_p1: "Most factories still rely on reactive maintenance and disconnected systems. Your engineers are firefighting instead of optimizing. Your CFO is writing checks instead of reinvesting.",
    problem_p2: "NovaTerra changes the equation — with a platform that monitors every asset, predicts every failure, and gives your team the intelligence to act before anything breaks.",
    problem_cta: "See How It Works →",
    pstat1_num: "23%",
    pstat1_desc: "average reduction in maintenance costs within 6 months",
    pstat2_num: "4.1x",
    pstat2_desc: "ROI reported by customers in year one",
    pstat3_num: "99.2%",
    pstat3_desc: "uptime achieved across NovaTerra-monitored assets",

    products_label: "The Platform",
    products_h2: "Two products. One connected factory.",
    product1_title: "AssetIQ",
    product1_desc: "Real-time health monitoring for every machine on your floor. Vibration, temperature, pressure — streamed, analyzed, visualized.",
    product1_li1: "Live sensor dashboards",
    product1_li2: "Anomaly detection with AI",
    product1_li3: "OEE tracking per asset",
    product1_li4: "Instant alert routing",
    product1_link: "Explore AssetIQ →",
    product2_title: "MaintainAI",
    product2_desc: "Predictive maintenance scheduling powered by machine learning. Stop guessing — start knowing when equipment will fail.",
    product2_li1: "Failure prediction (7–30 day horizon)",
    product2_li2: "Automated work order creation",
    product2_li3: "Parts & technician scheduling",
    product2_li4: "Salesforce & SAP integration",
    product2_link: "Explore MaintainAI →",

    testimonial_quote: "\"Before NovaTerra, we had three major line stoppages a quarter. In the 18 months since go-live, we've had zero. The ROI conversation with our CFO took about 90 seconds.\"",
    testimonial_cite: "— Markus Berger, Production Manager, PrecisionMetal AG",

    pricing_label: "Pricing",
    pricing_h2: "Simple, scalable pricing.",
    plan1_name: "Starter",
    plan1_price: "$1,200",
    plan1_period: "/mo",
    plan1_desc: "Up to 25 assets, 2 sites",
    plan1_li1: "AssetIQ monitoring",
    plan1_li2: "Email & Slack alerts",
    plan1_li3: "Standard dashboards",
    plan1_li4: "Community support",
    plan1_cta: "Get Started",
    plan2_name: "Growth",
    plan2_price: "$3,800",
    plan2_period: "/mo",
    plan2_desc: "Up to 100 assets, 5 sites",
    plan2_badge: "Most Popular",
    plan2_li1: "AssetIQ + MaintainAI",
    plan2_li2: "Predictive failure alerts",
    plan2_li3: "Salesforce / SAP integration",
    plan2_li4: "Dedicated CSM",
    plan2_cta: "Book a Demo",
    plan3_name: "Enterprise",
    plan3_price: "Custom",
    plan3_period: "",
    plan3_desc: "Unlimited assets & sites",
    plan3_li1: "Everything in Growth",
    plan3_li2: "Custom AI model training",
    plan3_li3: "On-prem / private cloud",
    plan3_li4: "SLA-backed support",
    plan3_cta: "Contact Sales",

    cta_h2: "See NovaTerra in action.",
    cta_p: "30-minute live demo. No pressure. No 47-slide decks.",
    cta_btn: "Book Your Demo",

    footer_tagline: "Industrial intelligence for the modern factory floor.",
    footer_products: "Products",
    footer_company: "Company",
    footer_about: "About",
    footer_careers: "Careers",
    footer_blog: "Blog",
    footer_support: "Support",
    footer_docs: "Documentation",
    footer_status: "Status",
    footer_contact: "Contact",
    footer_copy: "© 2025 NovaTerra Inc. All rights reserved.",

    // AssetIQ page
    assetiq_badge: "AssetIQ — Real-Time Monitoring",
    assetiq_h1: "Every machine. Every metric. In real time.",
    assetiq_sub: "AssetIQ connects your sensors to a unified dashboard — giving your team instant visibility into the health, performance, and status of every asset on the floor.",
    assetiq_cta1: "Book a Demo",
    assetiq_cta2: "See MaintainAI →",
    assetiq_features_label: "Features",
    assetiq_features_h2: "Built for the factory floor.",
    assetiq_f1_title: "Live Sensor Streams",
    assetiq_f1_desc: "Connect vibration, temperature, pressure, and current sensors via MQTT, OPC-UA, or Modbus. Data refreshes every 100ms.",
    assetiq_f2_title: "AI Anomaly Detection",
    assetiq_f2_desc: "Our models learn your machine's normal behavior and flag deviations before they become failures — with explainable alerts.",
    assetiq_f3_title: "OEE Tracking",
    assetiq_f3_desc: "Availability, Performance, Quality — tracked per asset, per shift, per line. Drill from plant-wide to individual machine in two clicks.",
    assetiq_f4_title: "Instant Alert Routing",
    assetiq_f4_desc: "Route alerts to the right person via Slack, Teams, SMS, or email — with escalation rules and on-call schedules built in.",
    assetiq_f5_title: "Custom Dashboards",
    assetiq_f5_desc: "Drag-and-drop dashboard builder. Share plant-wide KPIs with leadership and deep-dive views with your engineers.",
    assetiq_f6_title: "Historical Analysis",
    assetiq_f6_desc: "12 months of raw sensor data retained. Replay any event, compare shifts, and build your own reports.",
    assetiq_roi1_num: "40ms",
    assetiq_roi1_desc: "average alert latency",
    assetiq_roi2_num: "99.9%",
    assetiq_roi2_desc: "platform uptime SLA",
    assetiq_roi3_num: "2 weeks",
    assetiq_roi3_desc: "typical time to first value",
    assetiq_roi4_num: "500+",
    assetiq_roi4_desc: "sensor types supported",
    assetiq_integrations_h2: "Connects to your stack.",

    // MaintainAI page
    maintainai_badge: "MaintainAI — Predictive Maintenance",
    maintainai_h1: "Stop reacting. Start predicting.",
    maintainai_sub: "MaintainAI uses machine learning to forecast equipment failures up to 30 days in advance — automatically scheduling maintenance before anything breaks.",
    maintainai_cta1: "Book a Demo",
    maintainai_cta2: "← Back to AssetIQ",
    maintainai_features_label: "Features",
    maintainai_features_h2: "Maintenance intelligence, automated.",
    maintainai_f1_title: "Failure Prediction",
    maintainai_f1_desc: "ML models trained on your asset history predict failures 7–30 days out — with confidence scores and recommended actions.",
    maintainai_f2_title: "Automated Work Orders",
    maintainai_f2_desc: "When a failure is predicted, MaintainAI creates a work order in your CMMS automatically — no manual ticket needed.",
    maintainai_f3_title: "Parts Forecasting",
    maintainai_f3_desc: "Know which spare parts you'll need before you need them. Reduce emergency procurement by up to 60%.",
    maintainai_f4_title: "Technician Scheduling",
    maintainai_f4_desc: "Automatically match maintenance tasks to available technicians based on skills, shift patterns, and asset priority.",
    maintainai_f5_title: "Maintenance History",
    maintainai_f5_desc: "Full audit trail of every maintenance event, parts used, and technician actions — searchable and exportable.",
    maintainai_f6_title: "Continuous Learning",
    maintainai_f6_desc: "Models retrain automatically as new sensor data arrives — improving prediction accuracy over time without any manual tuning.",
    maintainai_roi1_num: "60%",
    maintainai_roi1_desc: "reduction in emergency parts procurement",
    maintainai_roi2_num: "30 days",
    maintainai_roi2_desc: "maximum failure prediction horizon",
    maintainai_roi3_num: "87%",
    maintainai_roi3_desc: "prediction accuracy (avg. across customers)",
    maintainai_roi4_num: "23%",
    maintainai_roi4_desc: "average maintenance cost reduction",
  },

  de: {
    nav_assetiq: "AssetIQ",
    nav_maintainai: "MaintainAI",
    nav_customers: "Kunden",
    nav_pricing: "Preise",
    nav_login: "Anmelden",
    nav_demo: "Demo anfragen",

    hero_badge: "Vertraut von über 400 Industrieunternehmen",
    hero_h1: "Ihre Maschinen sprechen.<br />Hören Sie zu?",
    hero_sub: "NovaTerra verbindet Ihre Produktionshalle mit Ihrer Geschäftsebene — Echtzeit-Asset-Transparenz, KI-gestützte Wartung und null ungeplante Ausfallzeiten.",
    hero_cta1: "Demo buchen",
    hero_cta2: "Plattform entdecken →",

    logos_label: "Vertraut von führenden Unternehmen",

    problem_h2: "Ungeplante Ausfallzeiten kosten Hersteller <span class='highlight'>230.000 € pro Stunde.</span>",
    problem_p1: "Die meisten Fabriken setzen noch immer auf reaktive Wartung und isolierte Systeme. Ihre Ingenieure kämpfen gegen Brände statt zu optimieren. Ihr CFO schreibt Schecks statt zu reinvestieren.",
    problem_p2: "NovaTerra ändert die Gleichung — mit einer Plattform, die jedes Asset überwacht, jeden Ausfall vorhersagt und Ihrem Team die Intelligenz gibt, zu handeln, bevor etwas bricht.",
    problem_cta: "So funktioniert es →",
    pstat1_num: "23 %",
    pstat1_desc: "durchschnittliche Senkung der Wartungskosten in 6 Monaten",
    pstat2_num: "4,1x",
    pstat2_desc: "ROI im ersten Jahr laut Kundenmeldungen",
    pstat3_num: "99,2 %",
    pstat3_desc: "Verfügbarkeit bei NovaTerra-überwachten Assets",

    products_label: "Die Plattform",
    products_h2: "Zwei Produkte. Eine vernetzte Fabrik.",
    product1_title: "AssetIQ",
    product1_desc: "Echtzeit-Gesundheitsüberwachung für jede Maschine auf Ihrem Shopfloor. Vibration, Temperatur, Druck — gestreamt, analysiert, visualisiert.",
    product1_li1: "Live-Sensor-Dashboards",
    product1_li2: "KI-gestützte Anomalieerkennung",
    product1_li3: "OEE-Tracking je Asset",
    product1_li4: "Sofortige Alarmweiterleitung",
    product1_link: "AssetIQ entdecken →",
    product2_title: "MaintainAI",
    product2_desc: "Vorausschauende Wartungsplanung durch Machine Learning. Aufhören zu raten — fangen Sie an zu wissen, wann Anlagen ausfallen.",
    product2_li1: "Ausfallvorhersage (7–30 Tage Horizont)",
    product2_li2: "Automatische Arbeitsauftragserstellung",
    product2_li3: "Ersatzteil- & Technikerplanung",
    product2_li4: "Salesforce- & SAP-Integration",
    product2_link: "MaintainAI entdecken →",

    testimonial_quote: "„Vor NovaTerra hatten wir drei größere Linienstopps pro Quartal. In den 18 Monaten seit dem Go-Live hatten wir keinen einzigen. Das ROI-Gespräch mit unserem CFO dauerte etwa 90 Sekunden."",
    testimonial_cite: "— Markus Berger, Produktionsleiter, PrecisionMetal AG",

    pricing_label: "Preise",
    pricing_h2: "Einfache, skalierbare Preise.",
    plan1_name: "Starter",
    plan1_price: "1.200 €",
    plan1_period: "/Monat",
    plan1_desc: "Bis zu 25 Assets, 2 Standorte",
    plan1_li1: "AssetIQ-Monitoring",
    plan1_li2: "E-Mail- & Slack-Alarme",
    plan1_li3: "Standard-Dashboards",
    plan1_li4: "Community-Support",
    plan1_cta: "Jetzt starten",
    plan2_name: "Growth",
    plan2_price: "3.800 €",
    plan2_period: "/Monat",
    plan2_desc: "Bis zu 100 Assets, 5 Standorte",
    plan2_badge: "Beliebteste Wahl",
    plan2_li1: "AssetIQ + MaintainAI",
    plan2_li2: "Vorausschauende Ausfallalarme",
    plan2_li3: "Salesforce- / SAP-Integration",
    plan2_li4: "Dedizierter Customer Success Manager",
    plan2_cta: "Demo buchen",
    plan3_name: "Enterprise",
    plan3_price: "Individuell",
    plan3_period: "",
    plan3_desc: "Unbegrenzte Assets & Standorte",
    plan3_li1: "Alles aus Growth",
    plan3_li2: "Individuelles KI-Modelltraining",
    plan3_li3: "On-Premise / Private Cloud",
    plan3_li4: "SLA-gesicherter Support",
    plan3_cta: "Vertrieb kontaktieren",

    cta_h2: "NovaTerra live erleben.",
    cta_p: "30-minütige Live-Demo. Kein Druck. Keine 47-Folien-Präsentation.",
    cta_btn: "Demo buchen",

    footer_tagline: "Industrielle Intelligenz für den modernen Shopfloor.",
    footer_products: "Produkte",
    footer_company: "Unternehmen",
    footer_about: "Über uns",
    footer_careers: "Karriere",
    footer_blog: "Blog",
    footer_support: "Support",
    footer_docs: "Dokumentation",
    footer_status: "Status",
    footer_contact: "Kontakt",
    footer_copy: "© 2025 NovaTerra GmbH. Alle Rechte vorbehalten.",

    // AssetIQ page
    assetiq_badge: "AssetIQ — Echtzeit-Monitoring",
    assetiq_h1: "Jede Maschine. Jede Kennzahl. In Echtzeit.",
    assetiq_sub: "AssetIQ verbindet Ihre Sensoren mit einem einheitlichen Dashboard — und gibt Ihrem Team sofortige Transparenz über Gesundheit, Leistung und Status jedes Assets.",
    assetiq_cta1: "Demo buchen",
    assetiq_cta2: "MaintainAI entdecken →",
    assetiq_features_label: "Funktionen",
    assetiq_features_h2: "Gebaut für den Shopfloor.",
    assetiq_f1_title: "Live-Sensor-Streams",
    assetiq_f1_desc: "Verbinden Sie Vibrations-, Temperatur-, Druck- und Stromsensoren via MQTT, OPC-UA oder Modbus. Daten aktualisieren sich alle 100 ms.",
    assetiq_f2_title: "KI-Anomalieerkennung",
    assetiq_f2_desc: "Unsere Modelle lernen das Normalverhalten Ihrer Maschine und melden Abweichungen, bevor sie zu Ausfällen werden — mit nachvollziehbaren Alarmen.",
    assetiq_f3_title: "OEE-Tracking",
    assetiq_f3_desc: "Verfügbarkeit, Leistung, Qualität — je Asset, je Schicht, je Linie erfasst. In zwei Klicks vom Werksüberblick zur einzelnen Maschine.",
    assetiq_f4_title: "Sofortige Alarmweiterleitung",
    assetiq_f4_desc: "Alarme direkt an die richtige Person — per Slack, Teams, SMS oder E-Mail — mit Eskalationsregeln und Bereitschaftsplänen.",
    assetiq_f5_title: "Individuelle Dashboards",
    assetiq_f5_desc: "Drag-and-Drop-Dashboard-Builder. Werksweite KPIs für die Geschäftsführung, Detailansichten für Ihre Ingenieure.",
    assetiq_f6_title: "Historische Analyse",
    assetiq_f6_desc: "12 Monate Roh-Sensordaten gespeichert. Jeden Vorfall wiedergeben, Schichten vergleichen und eigene Berichte erstellen.",
    assetiq_roi1_num: "40 ms",
    assetiq_roi1_desc: "durchschnittliche Alarm-Latenz",
    assetiq_roi2_num: "99,9 %",
    assetiq_roi2_desc: "Plattform-Verfügbarkeits-SLA",
    assetiq_roi3_num: "2 Wochen",
    assetiq_roi3_desc: "typische Zeit bis zum ersten Mehrwert",
    assetiq_roi4_num: "500+",
    assetiq_roi4_desc: "unterstützte Sensortypen",
    assetiq_integrations_h2: "Verbindet sich mit Ihrem Stack.",

    // MaintainAI page
    maintainai_badge: "MaintainAI — Vorausschauende Wartung",
    maintainai_h1: "Aufhören zu reagieren. Anfangen vorherzusagen.",
    maintainai_sub: "MaintainAI nutzt Machine Learning, um Anlagenausfälle bis zu 30 Tage im Voraus zu prognostizieren — und plant Wartungsarbeiten automatisch, bevor etwas bricht.",
    maintainai_cta1: "Demo buchen",
    maintainai_cta2: "← Zurück zu AssetIQ",
    maintainai_features_label: "Funktionen",
    maintainai_features_h2: "Wartungsintelligenz, automatisiert.",
    maintainai_f1_title: "Ausfallvorhersage",
    maintainai_f1_desc: "ML-Modelle, trainiert auf Ihrer Asset-Historie, prognostizieren Ausfälle 7–30 Tage im Voraus — mit Konfidenzwerten und empfohlenen Maßnahmen.",
    maintainai_f2_title: "Automatische Arbeitsaufträge",
    maintainai_f2_desc: "Wenn ein Ausfall prognostiziert wird, erstellt MaintainAI automatisch einen Arbeitsauftrag in Ihrem CMMS — kein manuelles Ticket nötig.",
    maintainai_f3_title: "Ersatzteilplanung",
    maintainai_f3_desc: "Wissen, welche Ersatzteile Sie benötigen, bevor Sie sie brauchen. Notfallbeschaffung um bis zu 60 % reduzieren.",
    maintainai_f4_title: "Technikerplanung",
    maintainai_f4_desc: "Wartungsaufgaben automatisch den verfügbaren Technikern zuweisen — basierend auf Qualifikationen, Schichtplänen und Asset-Priorität.",
    maintainai_f5_title: "Wartungshistorie",
    maintainai_f5_desc: "Vollständiges Protokoll jedes Wartungsvorgangs, verwendeter Teile und Technikeraktionen — durchsuchbar und exportierbar.",
    maintainai_f6_title: "Kontinuierliches Lernen",
    maintainai_f6_desc: "Modelle trainieren automatisch nach, wenn neue Sensordaten eintreffen — Vorhersagegenauigkeit steigt über Zeit ohne manuelles Eingreifen.",
    maintainai_roi1_num: "60 %",
    maintainai_roi1_desc: "weniger Notfallbeschaffungen für Ersatzteile",
    maintainai_roi2_num: "30 Tage",
    maintainai_roi2_desc: "maximaler Ausfallvorhersage-Horizont",
    maintainai_roi3_num: "87 %",
    maintainai_roi3_desc: "Vorhersagegenauigkeit (Ø über alle Kunden)",
    maintainai_roi4_num: "23 %",
    maintainai_roi4_desc: "durchschnittliche Senkung der Wartungskosten",
  }
};

function applyLang(lang) {
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.querySelectorAll('.lang-toggle button').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
  localStorage.setItem('nt-lang', lang);
  document.documentElement.lang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('nt-lang') || 'en';
  applyLang(saved);
  document.querySelectorAll('.lang-toggle button').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.getAttribute('data-lang')));
  });
});
