const translations = {
  en: {
    top_about: "About", top_support: "Support", top_contact: "Contact",
    logo_sub: "Precision Machines & Smart Factory",
    nav_machines: "Machines & Systems", nav_software: "Smart Factory",
    nav_stories: "Success Stories", nav_about: "Company",
    nav_contact: "Contact", nav_demo: "Request Demo",

    hero_eyebrow: "NEW — TerraLaser 3060 fiber · 12 kW",
    hero_h1: "Machines that cut.<br/>Software that thinks.",
    hero_sub: "NovaTerra builds the industrial machines that shape the world's most demanding parts — and the AI platform that keeps them running at peak performance.",
    hero_cta1: "Explore Machines", hero_cta2: "Request a Demo",
    mch_category: "Laser Cutting", mch_tagline: "High-speed fiber laser · 12 kW beam source",
    spec_power: "Laser Power", spec_format: "Format (mm)", spec_speed: "Max. Speed", spec_thickness: "Max. Thickness",
    bar_oee: "OEE", bar_uptime: "Uptime", bar_quality: "Quality",

    fig1: "Founded in Stuttgart, Germany", fig2: "Machines installed worldwide",
    fig3: "Countries with active customers", fig4: "Revenue invested in R&D",

    prod_eyebrow: "Machines & Systems", prod_h2: "The complete manufacturing portfolio.",
    prod_intro: "From laser cutting and bending to welding and automated storage — NovaTerra covers every step of the sheet metal process.",
    tile_laser_cat: "Laser Cutting", tile_laser_desc: "High-speed 2D fiber laser for sheet metal processing up to 30 mm. 12 kW beam source, automatic nozzle change, pallet changer.",
    tile_bend_cat: "Bending", tile_bend_desc: "CNC press brake with automatic tool change, AI-assisted angle correction and real-time springback compensation.",
    tile_weld_cat: "Laser Welding", tile_weld_desc: "Robotic laser welding cell for complex 3D weld seams. Integrated seam tracking, adaptive parameter control.",

    sf_eyebrow: "Smart Factory", sf_h2: "Your machines.<br/>Networked. Intelligent. Always on.",
    sf_p: "NovaTerra's software suite connects every machine on your floor into one live system — with AI that predicts failures before they happen and orchestrates your entire production flow.",
    sf_cta: "Discover Smart Factory →",
    sf_assetiq: "Real-time sensor monitoring — vibration, temperature, OEE per machine.",
    sf_maintainai: "Predictive maintenance — failure forecasts up to 30 days ahead.",
    sf_terraos: "Full production orchestration — job scheduling, material flow, reporting.",

    ind_eyebrow: "Industries", ind_h2: "Built for the most demanding sectors.",
    ind_auto: "Automotive", ind_auto_desc: "Body parts, battery enclosures, structural components. High volume, zero defects.",
    ind_aero: "Aerospace", ind_aero_desc: "Titanium and aluminium alloys. Tolerances to ±0.05 mm. Full traceability.",
    ind_med: "Medical Technology", ind_med_desc: "Surgical instruments, implant components. Clean room compatible systems.",
    ind_sheet: "Sheet Metal", ind_sheet_desc: "Job shops and contract manufacturers. Maximum flexibility, fast changeover.",

    story_eyebrow: "Success Stories", story_h2: "What our customers say.",
    st1_industry: "Sheet Metal · Germany",
    st1_quote: '"Since installing the TerraLaser 3060 and connecting it to AssetIQ, we\'ve eliminated unplanned downtime entirely. The machine pays for itself in every shift."',
    st1_cite: "— Markus Berger, Head of Production",
    st1_result: "Zero unplanned stoppages in 18 months. Maintenance costs down 31%.",
    st2_industry: "Automotive · Germany",
    st2_quote: '"The MaintainAI predictions gave us back control. We went from reactive to proactive overnight — and our line managers haven\'t had a sleepless night since."',
    st2_cite: "— Katrin Müller, VP Operations",
    st2_result: "87% prediction accuracy. Emergency procurement reduced by 60%.",
    story_all: "View all success stories →",

    cta_h3: "See NovaTerra in action.", cta_p: "30-minute live demo — machines, software, Smart Factory. No slides. Just results.",
    cta_demo: "Request Demo", cta_faq: "Browse FAQ",

    contact_h2: "Ready to talk to an expert?",
    contact_p: "Our application engineers are available for a no-obligation consultation — in German and English.",
    contact_btn: "Get in Touch",

    footer_brand: "Precision machines and smart factory software for industrial manufacturers worldwide.",
    footer_machines: "Machines", footer_software: "Software", footer_company: "Company",
    footer_about: "About NovaTerra", footer_stories: "Success Stories", footer_faq: "FAQ & Support",
    footer_copy: "© 2025 NovaTerra GmbH · Stuttgart, Germany",
    footer_privacy: "Privacy", footer_imprint: "Imprint", footer_terms: "Terms",

    // Machines page
    mach_eyebrow: "Machines & Systems", mach_h1: "Precision at every step of the process.",
    mach_sub: "From first cut to final bend — NovaTerra machines are engineered for reliability, speed and zero-defect output. Every machine ships with a 2-year performance guarantee and lifetime software updates.",
    mach_cta: "Request a Demo", mach_live: "Live Fleet Status",
    laser_h2: "The fastest fiber laser in its class.",
    laser_p: "The TerraLaser 3060 delivers 12 kW of fiber laser power in a rigid gantry frame — engineered for continuous 3-shift operation with automatic nozzle change, pallet changer, and real-time cut quality monitoring via AssetIQ.",
    laser_li1: "12 kW fiber beam source — cuts steel up to 30 mm, aluminium up to 25 mm",
    laser_li2: "Automatic nozzle change — zero manual intervention between materials",
    laser_li3: "Pallet changer — continuous loading, no dead time",
    laser_li4: "AssetIQ integration — live OEE, cut quality scoring, predictive maintenance",
    laser_li5: "Remote diagnostics via TerraConnect — service response in under 2 hours",
    laser_cta1: "Request Demo", laser_cta2: "Download Datasheet",
    bend_h2: "AI-assisted bending. First part correct.",
    bend_p: "The TerraBend 5000 combines a 320-tonne hydraulic press with AI-driven angle correction and real-time springback compensation. The result: first-part-correct bending, even on new materials, without test bends.",
    bend_li1: "320 t press force — handles steel up to 20 mm, aluminium up to 15 mm",
    bend_li2: "Automatic tool change — 8-station tool magazine, changeover in 45 seconds",
    bend_li3: "AI springback compensation — adapts to material batch variation automatically",
    bend_li4: "BendAssist offline programming — import from any CAD system",
    bend_li5: "MaintainAI integration — hydraulic pressure monitoring, seal wear prediction",
    bend_cta1: "Request Demo", bend_cta2: "Download Datasheet",
    weld_h2: "Robotic laser welding. Complex seams, perfect results.",
    weld_p: "The TerraWeld Cell combines a 4 kW fiber laser with a 6-axis robot arm and integrated seam tracking. Designed for complex 3D weld geometries in automotive, aerospace and heavy equipment manufacturing.",
    weld_li1: "4 kW fiber laser — deep penetration, minimal heat distortion",
    weld_li2: "6-axis robot — full 3D weld path freedom, ±0.05 mm repeatability",
    weld_li3: "Seam tracking — adapts in real time to fixture variation",
    weld_li4: "EasyWeld AI — automatic parameter optimisation from first weld",
    weld_li5: "Integrated quality camera — 100% inline weld inspection",
    weld_cta1: "Request Demo", weld_cta2: "Download Datasheet",
    specs_title: "Technical Specifications",
    spec_laser_power:"Laser power", spec_working_area:"Working area", spec_max_speed:"Max. positioning speed",
    spec_cut_speed:"Max. cutting speed (3mm steel)", spec_max_steel:"Max. thickness — mild steel",
    spec_max_alu:"Max. thickness — aluminium", spec_max_stainless:"Max. thickness — stainless",
    spec_repeatability:"Positioning repeatability", spec_footprint:"Machine footprint", spec_warranty:"Performance warranty",
    spec_press_force:"Press force", spec_work_length:"Working length", spec_daylight:"Daylight (open height)",
    spec_stroke_speed:"Stroke speed", spec_bend_steel:"Max. thickness — mild steel",
    spec_bend_alu:"Max. thickness — aluminium", spec_angle_acc:"Angle accuracy",
    spec_tool_stations:"Tool magazine stations", spec_changeover:"Tool changeover time",
    spec_weld_power:"Laser power", spec_robot_axes:"Robot axes", spec_weld_reach:"Robot reach",
    spec_weld_repeat:"Path repeatability", spec_weld_speed:"Max. welding speed",
    spec_weld_materials:"Materials", spec_weld_cell:"Cell footprint",
    mach_cta_h3: "Which machine is right for you?",
    mach_cta_p: "Talk to an application engineer — we'll recommend the right configuration for your materials, volumes and budget.",

    // Software page
    sw_eyebrow: "Smart Factory Suite", sw_h1: "One platform.<br/>Every machine. Zero downtime.",
    sw_sub: "NovaTerra's software suite turns your factory floor into a live, intelligent system — monitoring every sensor, predicting every failure, and orchestrating every job from order to dispatch.",
    sw_cta: "Request Demo",
    sw_fig1:"Average fleet uptime across customers", sw_fig2:"Avg. maintenance cost reduction in year 1",
    sw_fig3:"Failure prediction horizon with MaintainAI", sw_fig4:"Typical time-to-first-value after go-live",
    aiq_h2: "Every sensor. Every machine.<br/>In real time.",
    aiq_p: "AssetIQ connects to every NovaTerra machine via OPC-UA and streams vibration, temperature, pressure, and current data into a live dashboard — with AI anomaly detection that flags deviations before they become stoppages.",
    aiq_li1:"100ms data refresh — sub-second alert latency", aiq_li2:"AI anomaly detection — learns your machine's normal behaviour automatically",
    aiq_li3:"OEE per machine, per shift, per line — drill from fleet to sensor in 2 clicks",
    aiq_li4:"Alert routing — Slack, Teams, SMS, email with escalation rules",
    aiq_li5:"12 months data retention — replay any event, compare any shift",
    aiq_cta: "See AssetIQ Live",
    mai_h2: "Predict failures.<br/>Before they happen.",
    mai_p: "MaintainAI trains machine learning models on your machine's sensor history and predicts failures up to 30 days in advance — automatically creating work orders, ordering parts, and scheduling technicians before anything breaks.",
    mai_li1:"7–30 day failure prediction horizon with confidence scores",
    mai_li2:"Automatic work order creation in Salesforce, SAP, or IBM Maximo",
    mai_li3:"Parts forecasting — reduce emergency procurement by up to 60%",
    mai_li4:"Technician scheduling — matched by skill, shift and asset priority",
    mai_li5:"Continuous model retraining — accuracy improves over time automatically",
    mai_cta: "See MaintainAI Live",
    tos_h2: "Full production orchestration.<br/>From order to dispatch.",
    tos_p: "TerraOS is the production management layer that sits above your machines — scheduling jobs, managing material flow, tracking orders and generating shift reports. Integrates with SAP, Salesforce and all major ERP systems.",
    tos_li1:"Job scheduling — automatic sequencing by machine capacity, material and deadline",
    tos_li2:"Material flow — tracks sheet inventory, nesting efficiency, offcuts",
    tos_li3:"Order management — connected to your ERP, live delivery status",
    tos_li4:"Shift reporting — automated OEE, throughput, scrap reports every shift",
    tos_li5:"Salesforce integration — service cases, field service, asset records synced live",
    tos_cta: "See TerraOS Live",
    int_eyebrow: "Integrations", int_h3: "Works with your existing stack.",
    sw_cta_h3: "See the Smart Factory suite live.",
    sw_cta_p: "30-minute demo — AssetIQ, MaintainAI, TerraOS connected to a live machine feed.",

    // Success Stories
    ss_eyebrow: "Success Stories", ss_h1: "Results that speak<br/>for themselves.",
    ss_sub: "From German sheet metal shops to UK aerospace suppliers — NovaTerra customers achieve measurable results within the first 90 days of go-live.",
    s1_label:"Sheet Metal · Germany", s1_h2:"PrecisionMetal AG eliminates unplanned downtime after TerraLaser 3060 install.",
    s1_p:"PrecisionMetal AG operates three production lines in Stuttgart processing 8,000 tonnes of sheet steel per year for the automotive and construction sectors. Before NovaTerra, unplanned stoppages averaged 4.2 per month — costing an estimated €180,000 per year in lost production and emergency maintenance.",
    s1_quote:'"Since connecting AssetIQ to our TerraLaser 3060, we haven\'t had a single unplanned stoppage. The system flagged a coolant pump issue 11 days before it would have failed — our team fixed it in a scheduled maintenance slot. That alone paid for the software in the first month."',
    s1_cite:"— Markus Berger, Head of Production, PrecisionMetal AG",
    s1_p2:"Products used: TerraLaser 3060, AssetIQ, MaintainAI",
    s1_r1:"Unplanned stoppages in 18 months after go-live (vs. 4.2/month before)",
    s1_r2:"Reduction in total maintenance costs year-on-year",
    s1_r3:"Annual saving from eliminated emergency maintenance and lost production",
    s1_r4:"Earliest advance warning received from MaintainAI — coolant pump failure avoided",
    s2_label:"Automotive · Germany", s2_h2:"Nexora Automotive goes from reactive to predictive across 5 production sites.",
    s2_p:"Nexora Automotive GmbH manufactures body-in-white components and battery enclosures for three major German OEMs. With five sites and 34 laser and bending machines in operation, uncoordinated maintenance was their biggest operational challenge.",
    s2_quote:'"MaintainAI gave us back control. We went from reactive to proactive overnight. My team hasn\'t had a sleepless Sunday in 14 months."',
    s2_cite:"— Katrin Müller, VP Operations, Nexora Automotive GmbH",
    s2_p2:"Products used: AssetIQ, MaintainAI, TerraOS, SAP integration",
    s2_r1:"Failure prediction accuracy across 34 machines at 5 sites",
    s2_r2:"Reduction in emergency spare parts procurement",
    s2_r3:"ROI in year one — achieved in month 9",
    s2_r4:"All connected to one TerraOS dashboard within 6 weeks of go-live",
    s3_label:"Aerospace · United Kingdom", s3_h2:"AeroFab UK achieves ±0.03mm consistency on titanium components with TerraLaser.",
    s3_p:"AeroFab UK supplies precision laser-cut titanium and aluminium components to Tier 1 aerospace contractors. Rework rates were running at 7.2% with the previous supplier. After switching to TerraLaser 3060, rework dropped to under 0.8% in the first quarter.",
    s3_quote:'"The cut quality consistency on titanium is in a different league. We\'re hitting ±0.03mm on 4mm titanium sheet — day in, day out. We\'ve already ordered a second machine."',
    s3_cite:"— James Whitfield, Head of Manufacturing, AeroFab UK",
    s3_p2:"Products used: TerraLaser 3060, TerraWeld Cell, AssetIQ",
    s3_r1:"Rework rate (down from 7.2% with previous supplier)",
    s3_r2:"Cut consistency on 4mm titanium — every part, every shift",
    s3_r3:"Ordered within 8 months of first installation",
    s3_r4:"Audit passed first time — cut quality specifically commended",
    s4_label:"Medical Technology · Switzerland", s4_h2:"MedForm AG cuts surgical instrument production cycle time by 34%.",
    s4_p:"MedForm AG manufactures stainless steel and titanium surgical instruments for distribution across Europe and North America. Tight delivery windows and zero-defect requirements made their previous bending and cutting process a constant bottleneck.",
    s4_quote:'"We went from a 4-hour changeover between instrument families to under 45 minutes. We\'ve taken on 30% more orders without adding a single shift."',
    s4_cite:"— Sophie van der Berg, Director of Operations, MedForm AG",
    s4_p2:"Products used: TerraBend 5000, TerraOS, MaintainAI",
    s4_r1:"Reduction in production cycle time per instrument batch",
    s4_r2:"Changeover time (down from 4 hours with previous machine)",
    s4_r3:"Order volume increase — no additional shifts or headcount",
    s4_r4:"Full traceability maintained — audit trail generated automatically by TerraOS",
    ss_cta_h2:"Your results start here.",
    ss_cta_p:"Book a 30-minute demo and we'll show you exactly what NovaTerra can deliver for your specific production environment.",
  },

  de: {
    top_about: "Über uns", top_support: "Support", top_contact: "Kontakt",
    logo_sub: "Präzisionsmaschinen & Smart Factory",
    nav_machines: "Maschinen & Systeme", nav_software: "Smart Factory",
    nav_stories: "Erfolgsgeschichten", nav_about: "Unternehmen",
    nav_contact: "Kontakt", nav_demo: "Demo anfragen",

    hero_eyebrow: "NEU — TerraLaser 3060 Faser · 12 kW",
    hero_h1: "Maschinen, die schneiden.<br/>Software, die denkt.",
    hero_sub: "NovaTerra baut die Industriemaschinen, die die anspruchsvollsten Bauteile der Welt formen — und die KI-Plattform, die sie dauerhaft auf Höchstleistung hält.",
    hero_cta1: "Maschinen entdecken", hero_cta2: "Demo anfragen",
    mch_category: "Laserschneiden", mch_tagline: "Hochgeschwindigkeits-Faserlaser · 12 kW Strahlquelle",
    spec_power: "Laserleistung", spec_format: "Format (mm)", spec_speed: "Höchstgeschwindigkeit", spec_thickness: "Max. Materialdicke",
    bar_oee: "OEE", bar_uptime: "Verfügbarkeit", bar_quality: "Qualität",

    fig1: "Gegründet in Stuttgart, Deutschland", fig2: "Installierte Maschinen weltweit",
    fig3: "Länder mit aktiven Kunden", fig4: "Umsatz investiert in F&amp;E",

    prod_eyebrow: "Maschinen & Systeme", prod_h2: "Das vollständige Fertigungsportfolio.",
    prod_intro: "Vom Laserschneiden über Biegen bis hin zu Schweißen und automatisierter Lagerung — NovaTerra deckt jeden Schritt der Blechbearbeitung ab.",
    tile_laser_cat: "Laserschneiden", tile_laser_desc: "Hochgeschwindigkeits-2D-Faserlaser für die Blechbearbeitung bis 30 mm. 12 kW Strahlquelle, automatischer Düsenwechsel, Palettenwechsler.",
    tile_bend_cat: "Biegen", tile_bend_desc: "CNC-Abkantpresse mit automatischem Werkzeugwechsel, KI-gestützter Winkelkorrektur und Rückfederungsausgleich in Echtzeit.",
    tile_weld_cat: "Laserschweißen", tile_weld_desc: "Roboter-Laserschweißzelle für komplexe 3D-Schweißnähte. Integrierte Nahtverfolgung, adaptive Parametersteuerung.",

    sf_eyebrow: "Smart Factory", sf_h2: "Ihre Maschinen.<br/>Vernetzt. Intelligent. Immer einsatzbereit.",
    sf_p: "Die Softwaresuite von NovaTerra verbindet jede Maschine auf Ihrem Shopfloor zu einem einzigen Live-System — mit KI, die Ausfälle vorhersagt, bevor sie passieren, und Ihren gesamten Produktionsfluss orchestriert.",
    sf_cta: "Smart Factory entdecken →",
    sf_assetiq: "Echtzeit-Sensor-Monitoring — Vibration, Temperatur, OEE je Maschine.",
    sf_maintainai: "Vorausschauende Wartung — Ausfallprognosen bis zu 30 Tage im Voraus.",
    sf_terraos: "Vollständige Produktionsorchestrierung — Auftragsplanung, Materialfluss, Reporting.",

    ind_eyebrow: "Branchen", ind_h2: "Gebaut für die anspruchsvollsten Sektoren.",
    ind_auto: "Automobilindustrie", ind_auto_desc: "Karosserieteile, Batteriegehäuse, Strukturbauteile. Hohe Stückzahlen, null Fehler.",
    ind_aero: "Luft- und Raumfahrt", ind_aero_desc: "Titan- und Aluminiumlegierungen. Toleranzen bis ±0,05 mm. Vollständige Rückverfolgbarkeit.",
    ind_med: "Medizintechnik", ind_med_desc: "Chirurgische Instrumente, Implantatkomponenten. Reinraumkompatible Systeme.",
    ind_sheet: "Blechverarbeitung", ind_sheet_desc: "Lohnfertiger und Auftragsbetriebe. Maximale Flexibilität, schneller Rüstwechsel.",

    story_eyebrow: "Erfolgsgeschichten", story_h2: "Was unsere Kunden sagen.",
    st1_industry: "Blechverarbeitung · Deutschland",
    st1_quote: '„Seit wir den TerraLaser 3060 mit AssetIQ verbunden haben, hatten wir keine einzige ungeplante Abschaltung mehr. Die Maschine rechnet sich mit jeder Schicht."',
    st1_cite: "— Markus Berger, Produktionsleiter",
    st1_result: "Null ungeplante Stopps in 18 Monaten. Wartungskosten um 31 % gesunken.",
    st2_industry: "Automobilindustrie · Deutschland",
    st2_quote: '„MaintainAI hat uns die Kontrolle zurückgegeben. Wir sind über Nacht von reaktiv zu proaktiv geworden — unsere Schichtleiter haben seitdem keine schlaflosen Nächte mehr."',
    st2_cite: "— Katrin Müller, VP Operations",
    st2_result: "87 % Vorhersagegenauigkeit. Notfallbeschaffungen um 60 % reduziert.",
    story_all: "Alle Erfolgsgeschichten ansehen →",

    cta_h3: "NovaTerra live erleben.", cta_p: "30-minütige Live-Demo — Maschinen, Software, Smart Factory. Keine Folien. Nur Ergebnisse.",
    cta_demo: "Demo anfragen", cta_faq: "FAQ durchsuchen",

    contact_h2: "Bereit, mit einem Experten zu sprechen?",
    contact_p: "Unsere Applikationsingenieure stehen für ein unverbindliches Beratungsgespräch zur Verfügung — auf Deutsch und Englisch.",
    contact_btn: "Jetzt Kontakt aufnehmen",

    footer_brand: "Präzisionsmaschinen und Smart-Factory-Software für Industriehersteller weltweit.",
    footer_machines: "Maschinen", footer_software: "Software", footer_company: "Unternehmen",
    footer_about: "Über NovaTerra", footer_stories: "Erfolgsgeschichten", footer_faq: "FAQ & Support",
    footer_copy: "© 2025 NovaTerra GmbH · Stuttgart, Deutschland",
    footer_privacy: "Datenschutz", footer_imprint: "Impressum", footer_terms: "AGB",

    mach_eyebrow: "Maschinen & Systeme", mach_h1: "Präzision in jedem Prozessschritt.",
    mach_sub: "Vom ersten Schnitt bis zur letzten Biegung — NovaTerra-Maschinen sind auf Zuverlässigkeit, Geschwindigkeit und fehlerfreie Produktion ausgelegt. Jede Maschine wird mit 2 Jahren Leistungsgarantie und lebenslangen Software-Updates geliefert.",
    mach_cta: "Demo anfragen", mach_live: "Live-Flottenstatus",
    laser_h2: "Der schnellste Faserlaser seiner Klasse.",
    laser_p: "Der TerraLaser 3060 liefert 12 kW Faserlaserleistung in einem steifen Portalrahmen — ausgelegt für den Dauerbetrieb im 3-Schicht-Betrieb mit automatischem Düsenwechsel, Palettenwechsler und Echtzeit-Schnittqualitätsüberwachung via AssetIQ.",
    laser_li1: "12 kW Faserstrahlquelle — schneidet Stahl bis 30 mm, Aluminium bis 25 mm",
    laser_li2: "Automatischer Düsenwechsel — kein manueller Eingriff beim Materialwechsel",
    laser_li3: "Palettenwechsler — Dauerbetrieb ohne Totzeiten",
    laser_li4: "AssetIQ-Integration — Live-OEE, Schnittqualitätsbewertung, vorausschauende Wartung",
    laser_li5: "Ferndiagnose via TerraConnect — Servicereaktion in unter 2 Stunden",
    laser_cta1: "Demo anfragen", laser_cta2: "Datenblatt herunterladen",
    bend_h2: "KI-gestütztes Biegen. Erstes Teil korrekt.",
    bend_p: "Die TerraBend 5000 kombiniert eine 320-Tonnen-Hydraulikpresse mit KI-gesteuerter Winkelkorrektur und Rückfederungsausgleich in Echtzeit. Das Ergebnis: Erstteile-Korrektheit, auch bei neuen Werkstoffen, ohne Testbiegungen.",
    bend_li1: "320 t Presskraft — verarbeitet Stahl bis 20 mm, Aluminium bis 15 mm",
    bend_li2: "Automatischer Werkzeugwechsel — 8-Station-Werkzeugmagazin, Wechsel in 45 Sekunden",
    bend_li3: "KI-Rückfederungsausgleich — passt sich automatisch an Chargenstreuung an",
    bend_li4: "BendAssist Offline-Programmierung — Import aus jedem CAD-System",
    bend_li5: "MaintainAI-Integration — Hydraulikdrucküberwachung, Dichtungsverschleißprognose",
    bend_cta1: "Demo anfragen", bend_cta2: "Datenblatt herunterladen",
    weld_h2: "Roboter-Laserschweißen. Komplexe Nähte, perfekte Ergebnisse.",
    weld_p: "Die TerraWeld Cell kombiniert einen 4-kW-Faserlaser mit einem 6-Achs-Roboterarm und integrierter Nahtverfolgung. Entwickelt für komplexe 3D-Schweißgeometrien in der Automobil-, Luft- und Schwerindustrie.",
    weld_li1: "4 kW Faserlaser — Tiefschweißen, minimaler Wärmeverzug",
    weld_li2: "6-Achs-Roboter — volle 3D-Schweißpfadfreiheit, ±0,05 mm Wiederholgenauigkeit",
    weld_li3: "Nahtverfolgung — passt sich in Echtzeit an Vorrichtungsstreuung an",
    weld_li4: "EasyWeld KI — automatische Parameteroptimierung ab der ersten Schweißnaht",
    weld_li5: "Integrierte Qualitätskamera — 100 % inline-Schweißnahtprüfung",
    weld_cta1: "Demo anfragen", weld_cta2: "Datenblatt herunterladen",
    specs_title: "Technische Daten",
    spec_laser_power:"Laserleistung", spec_working_area:"Arbeitsbereich", spec_max_speed:"Max. Verfahrgeschwindigkeit",
    spec_cut_speed:"Max. Schneidgeschwindigkeit (3mm Stahl)", spec_max_steel:"Max. Dicke — Baustahl",
    spec_max_alu:"Max. Dicke — Aluminium", spec_max_stainless:"Max. Dicke — Edelstahl",
    spec_repeatability:"Positionierwiederholgenauigkeit", spec_footprint:"Maschinenaufstellmaß", spec_warranty:"Leistungsgarantie",
    spec_press_force:"Presskraft", spec_work_length:"Arbeitslänge", spec_daylight:"Öffnungshöhe",
    spec_stroke_speed:"Hubgeschwindigkeit", spec_bend_steel:"Max. Dicke — Baustahl",
    spec_bend_alu:"Max. Dicke — Aluminium", spec_angle_acc:"Winkelgenauigkeit",
    spec_tool_stations:"Werkzeugmagazinstationen", spec_changeover:"Werkzeugwechselzeit",
    spec_weld_power:"Laserleistung", spec_robot_axes:"Roboterachsen", spec_weld_reach:"Roboterreichweite",
    spec_weld_repeat:"Bahnwiederholgenauigkeit", spec_weld_speed:"Max. Schweißgeschwindigkeit",
    spec_weld_materials:"Werkstoffe", spec_weld_cell:"Zellenaufstellmaß",
    mach_cta_h3: "Welche Maschine passt zu Ihnen?",
    mach_cta_p: "Sprechen Sie mit einem Applikationsingenieur — wir empfehlen die richtige Konfiguration für Ihre Werkstoffe, Stückzahlen und Ihr Budget.",

    sw_eyebrow: "Smart Factory Suite", sw_h1: "Eine Plattform.<br/>Jede Maschine. Null Ausfallzeit.",
    sw_sub: "Die Softwaresuite von NovaTerra macht Ihren Shopfloor zu einem lebendigen, intelligenten System — jeder Sensor überwacht, jeder Ausfall vorhergesagt, jeder Auftrag von der Bestellung bis zum Versand orchestriert.",
    sw_cta: "Demo anfragen",
    sw_fig1:"Durchschnittliche Flottenverfügbarkeit bei Kunden", sw_fig2:"Ø Senkung der Wartungskosten im Jahr 1",
    sw_fig3:"Ausfallvorhersage-Horizont mit MaintainAI", sw_fig4:"Typische Zeit bis zum ersten Mehrwert nach Go-live",
    aiq_h2: "Jeder Sensor. Jede Maschine.<br/>In Echtzeit.",
    aiq_p: "AssetIQ verbindet sich mit jeder NovaTerra-Maschine via OPC-UA und streamt Vibrations-, Temperatur-, Druck- und Stromdaten in ein Live-Dashboard — mit KI-Anomalieerkennung, die Abweichungen meldet, bevor sie zu Stopps werden.",
    aiq_li1:"100-ms-Datenaktualisierung — Sub-Sekunden-Alarmlatenz",
    aiq_li2:"KI-Anomalieerkennung — lernt automatisch das Normalverhalten Ihrer Maschine",
    aiq_li3:"OEE je Maschine, je Schicht, je Linie — in 2 Klicks von der Flottenansicht zum Sensor",
    aiq_li4:"Alarmweiterleitung — Slack, Teams, SMS, E-Mail mit Eskalationsregeln",
    aiq_li5:"12 Monate Datenspeicherung — jeden Vorfall wiedergeben, jede Schicht vergleichen",
    aiq_cta: "AssetIQ live erleben",
    mai_h2: "Ausfälle vorhersagen.<br/>Bevor sie passieren.",
    mai_p: "MaintainAI trainiert Machine-Learning-Modelle auf der Sensorhistorie Ihrer Maschine und sagt Ausfälle bis zu 30 Tage im Voraus vorher — erstellt automatisch Arbeitsaufträge, bestellt Teile und plant Techniker, bevor etwas kaputt geht.",
    mai_li1:"7–30 Tage Ausfallvorhersage-Horizont mit Konfidenzwerten",
    mai_li2:"Automatische Arbeitsauftragserstellung in Salesforce, SAP oder IBM Maximo",
    mai_li3:"Ersatzteilprognose — Notfallbeschaffungen um bis zu 60 % reduzieren",
    mai_li4:"Technikerplanung — nach Qualifikation, Schicht und Asset-Priorität",
    mai_li5:"Kontinuierliches Modell-Retraining — Genauigkeit steigt automatisch über Zeit",
    mai_cta: "MaintainAI live erleben",
    tos_h2: "Vollständige Produktionsorchestrierung.<br/>Von der Bestellung bis zum Versand.",
    tos_p: "TerraOS ist die Produktionsmanagement-Ebene über Ihren Maschinen — plant Aufträge, managt Materialfluss, verfolgt Bestellungen und erstellt Schichtberichte. Integriert mit SAP, Salesforce und allen gängigen ERP-Systemen.",
    tos_li1:"Auftragsplanung — automatische Sequenzierung nach Maschinenkapazität, Material und Termin",
    tos_li2:"Materialfluss — verfolgt Blechbestand, Verschachtelungseffizienz, Restteile",
    tos_li3:"Auftragsmanagement — mit Ihrem ERP verbunden, Live-Lieferstatus",
    tos_li4:"Schichtreporting — automatisierte OEE-, Durchsatz- und Ausschussberichte jede Schicht",
    tos_li5:"Salesforce-Integration — Service-Cases, Field Service, Asset-Datensätze live synchronisiert",
    tos_cta: "TerraOS live erleben",
    int_eyebrow: "Integrationen", int_h3: "Passt in Ihren bestehenden Stack.",
    sw_cta_h3: "Smart Factory Suite live erleben.",
    sw_cta_p: "30-minütige Demo — AssetIQ, MaintainAI, TerraOS mit einem Live-Maschinen-Feed verbunden.",

    ss_eyebrow: "Erfolgsgeschichten", ss_h1: "Ergebnisse, die für sich sprechen.",
    ss_sub: "Von deutschen Blechfertigern bis zu britischen Luftfahrtzulieferern — NovaTerra-Kunden erzielen messbare Ergebnisse innerhalb der ersten 90 Tage nach Go-live.",
    s1_label:"Blechverarbeitung · Deutschland", s1_h2:"PrecisionMetal AG eliminiert ungeplante Ausfallzeiten nach TerraLaser-3060-Installation.",
    s1_p:"PrecisionMetal AG betreibt drei Fertigungslinien in Stuttgart und verarbeitet 8.000 Tonnen Stahlblech pro Jahr für die Automobil- und Baubranche. Vor NovaTerra lagen ungeplante Stopps bei durchschnittlich 4,2 pro Monat.",
    s1_quote:'„Seit wir AssetIQ mit unserem TerraLaser 3060 verbunden haben, hatten wir keinen einzigen ungeplanten Stopp mehr. Das System hat ein Kühlmittelpumpenproblem 11 Tage vor dem Ausfall gemeldet. Das allein hat die Software im ersten Monat bezahlt."',
    s1_cite:"— Markus Berger, Produktionsleiter, PrecisionMetal AG",
    s1_p2:"Eingesetzte Produkte: TerraLaser 3060, AssetIQ, MaintainAI",
    s1_r1:"Ungeplante Stopps in 18 Monaten nach Go-live (vorher 4,2/Monat)",
    s1_r2:"Senkung der Gesamtwartungskosten im Jahresvergleich",
    s1_r3:"Jährliche Einsparung durch eliminierte Notfallwartungen und Produktionsausfälle",
    s1_r4:"Früheste Vorwarnung von MaintainAI — Ausfall der Kühlmittelpumpe verhindert",
    s2_label:"Automobilindustrie · Deutschland", s2_h2:"Nexora Automotive wechselt an 5 Standorten von reaktiv zu vorausschauend.",
    s2_p:"Nexora Automotive GmbH fertigt Rohbauteile und Batteriegehäuse für drei große deutsche OEMs. Mit fünf Standorten und 34 Laser- und Biegemaschinen war unkoordinierte Wartung die größte operative Herausforderung.",
    s2_quote:'„MaintainAI hat uns die Kontrolle zurückgegeben. Mein Team hatte seit 14 Monaten keine schlaflosen Sonntage mehr."',
    s2_cite:"— Katrin Müller, VP Operations, Nexora Automotive GmbH",
    s2_p2:"Eingesetzte Produkte: AssetIQ, MaintainAI, TerraOS, SAP-Integration",
    s2_r1:"Vorhersagegenauigkeit über 34 Maschinen an 5 Standorten",
    s2_r2:"Senkung der Notfallbeschaffungen für Ersatzteile",
    s2_r3:"ROI im Jahr 1 — erreicht in Monat 9",
    s2_r4:"Alle Standorte innerhalb von 6 Wochen an ein TerraOS-Dashboard angebunden",
    s3_label:"Luft- und Raumfahrt · Vereinigtes Königreich", s3_h2:"AeroFab UK erreicht ±0,03-mm-Konsistenz bei Titanbauteilen mit dem TerraLaser.",
    s3_p:"AeroFab UK liefert präzisions-lasergeschnittene Titan- und Aluminiumbauteile an Tier-1-Luft- und Raumfahrtauftragnehmer. Mit dem vorherigen Anbieter lag die Nacharbeitsquote bei 7,2 %.",
    s3_quote:'„Die Schnittqualitätskonsistenz bei Titan ist in einer anderen Liga. Wir erreichen ±0,03 mm auf 4-mm-Titanblech — Tag für Tag. Wir haben bereits eine zweite Maschine bestellt."',
    s3_cite:"— James Whitfield, Head of Manufacturing, AeroFab UK",
    s3_p2:"Eingesetzte Produkte: TerraLaser 3060, TerraWeld Cell, AssetIQ",
    s3_r1:"Nacharbeitsquote (von 7,2 % beim Vorgängeranbieter)",
    s3_r2:"Schnittkonsistenz auf 4-mm-Titanblech — jedes Teil, jede Schicht",
    s3_r3:"Zweite Maschine innerhalb von 8 Monaten nach Erstinstallation bestellt",
    s3_r4:"AS9100-Audit beim ersten Mal bestanden — Schnittqualität ausdrücklich gelobt",
    s4_label:"Medizintechnik · Schweiz", s4_h2:"MedForm AG senkt Produktionszykluszeit für Chirurgieinstrumente um 34 %.",
    s4_p:"MedForm AG fertigt chirurgische Instrumente aus Edelstahl und Titan für den Vertrieb in Europa und Nordamerika. Enge Liefertermine und Null-Fehler-Anforderungen machten den bisherigen Biege- und Schneidprozess zum ständigen Engpass.",
    s4_quote:'„Wir sind von einem 4-Stunden-Umrüsten zwischen Instrumentenfamilien auf unter 45 Minuten gekommen. Wir haben 30 % mehr Aufträge angenommen, ohne eine einzige Schicht hinzuzufügen."',
    s4_cite:"— Sophie van der Berg, Director of Operations, MedForm AG",
    s4_p2:"Eingesetzte Produkte: TerraBend 5000, TerraOS, MaintainAI",
    s4_r1:"Senkung der Produktionszykluszeit je Instrumentencharge",
    s4_r2:"Rüstzeit (von 4 Stunden mit der Vorgängermaschine)",
    s4_r3:"Mehr Auftragsvolumen — keine zusätzlichen Schichten oder Mitarbeiter",
    s4_r4:"Vollständige Rückverfolgbarkeit — Prüfprotokoll automatisch durch TerraOS erstellt",
    ss_cta_h2:"Ihre Ergebnisse beginnen hier.",
    ss_cta_p:"Buchen Sie eine 30-minütige Demo und wir zeigen Ihnen genau, was NovaTerra für Ihre spezifische Produktionsumgebung leisten kann.",
  }
};

function applyLang(lang) {
  const t = translations[lang];
  if (!t) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.querySelectorAll('.lang-toggle button').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
  localStorage.setItem('nt-lang', lang);
  document.documentElement.lang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('nt-lang') || 'en';
  applyLang(saved);
  document.querySelectorAll('.lang-toggle button').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.getAttribute('data-lang')));
  });
});
